language: node_js

node_js:
  - stable

install: 
  - npm install

script: 
  - npm run test

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_success: npm run coverage